/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Local Shop Management API
 * OpenAPI spec version: v1
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateOrderRequest,
  CreateProductRequest,
  CreateShopRequest,
  CreateShopkeeperRequest,
  LoginRequest,
  RegisterRequest,
  UpdateOrderStatusRequest,
  UpdateProductRequest
} from './model';




  export const getLocalShopManagementAPI = (axiosInstance: AxiosInstance = axios) => {
const postApiAdminCreateShopkeeper = (
    createShopkeeperRequest?: CreateShopkeeperRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/Admin/create-shopkeeper`,
      createShopkeeperRequest,options
    );
  }

const postApiAuthRegister = (
    registerRequest?: RegisterRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/Auth/register`,
      registerRequest,options
    );
  }

const postApiAuthLogin = (
    loginRequest?: LoginRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/Auth/login`,
      loginRequest,options
    );
  }

const postApiOrder = (
    createOrderRequest?: CreateOrderRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/Order`,
      createOrderRequest,options
    );
  }

const getApiOrderMyOrders = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/Order/my-orders`,options
    );
  }

const getApiOrderShopOrders = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/Order/shop-orders`,options
    );
  }

const putApiOrderIdStatus = (
    id: string,
    updateOrderStatusRequest?: UpdateOrderStatusRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.put(
      `/api/Order/${id}/status`,
      updateOrderStatusRequest,options
    );
  }

const postApiProduct = (
    createProductRequest?: CreateProductRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/Product`,
      createProductRequest,options
    );
  }

const getApiProductMyProducts = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/Product/my-products`,options
    );
  }

const getApiProductId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/Product/${id}`,options
    );
  }

const putApiProductId = (
    id: string,
    updateProductRequest?: UpdateProductRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.put(
      `/api/Product/${id}`,
      updateProductRequest,options
    );
  }

const deleteApiProductId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/Product/${id}`,options
    );
  }

const postApiShop = (
    createShopRequest?: CreateShopRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/Shop`,
      createShopRequest,options
    );
  }

const getApiShop = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/Shop`,options
    );
  }

const getApiShopId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/Shop/${id}`,options
    );
  }

return {postApiAdminCreateShopkeeper,postApiAuthRegister,postApiAuthLogin,postApiOrder,getApiOrderMyOrders,getApiOrderShopOrders,putApiOrderIdStatus,postApiProduct,getApiProductMyProducts,getApiProductId,putApiProductId,deleteApiProductId,postApiShop,getApiShop,getApiShopId}};
export type PostApiAdminCreateShopkeeperResult = AxiosResponse<void>
export type PostApiAuthRegisterResult = AxiosResponse<void>
export type PostApiAuthLoginResult = AxiosResponse<void>
export type PostApiOrderResult = AxiosResponse<void>
export type GetApiOrderMyOrdersResult = AxiosResponse<void>
export type GetApiOrderShopOrdersResult = AxiosResponse<void>
export type PutApiOrderIdStatusResult = AxiosResponse<void>
export type PostApiProductResult = AxiosResponse<void>
export type GetApiProductMyProductsResult = AxiosResponse<void>
export type GetApiProductIdResult = AxiosResponse<void>
export type PutApiProductIdResult = AxiosResponse<void>
export type DeleteApiProductIdResult = AxiosResponse<void>
export type PostApiShopResult = AxiosResponse<void>
export type GetApiShopResult = AxiosResponse<void>
export type GetApiShopIdResult = AxiosResponse<void>
