/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Local Shop Management API
 * OpenAPI spec version: v1
 */

export interface CreateOrderItemRequest {
  /** @nullable */
  productId?: string | null;
  quantity?: number;
}
