/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Local Shop Management API
 * OpenAPI spec version: v1
 */

export interface CreateShopRequest {
  /** @nullable */
  shopName?: string | null;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  category?: string | null;
  latitude?: number;
  longitude?: number;
}
