/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Local Shop Management API
 * OpenAPI spec version: v1
 */
import type { CreateOrderItemRequest } from './createOrderItemRequest';

export interface CreateOrderRequest {
  /** @nullable */
  shopId?: string | null;
  /** @nullable */
  items?: CreateOrderItemRequest[] | null;
  customerLatitude?: number;
  customerLongitude?: number;
}
