/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Local Shop Management API
 * OpenAPI spec version: v1
 */

export type OrderStatus = typeof OrderStatus[keyof typeof OrderStatus];


export const OrderStatus = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
} as const;
