/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Local Shop Management API
 * OpenAPI spec version: v1
 */

export interface UpdateProductRequest {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  price?: number;
  stock?: number;
  /** @nullable */
  category?: string | null;
  isAvailable?: boolean;
}
