/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Local Shop Management API
 * OpenAPI spec version: v1
 */
import type { OrderStatus } from './orderStatus';

export interface UpdateOrderStatusRequest {
  status?: OrderStatus;
}
